/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.rendering.PDFRenderer;

import java.awt.Graphics;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.JPanel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.io.IOException;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;


/**
 *
 * @author Carlos
 */
public class frmVisualizadorPDF extends javax.swing.JFrame {

    private BufferedImage imagenPDF;
    private PDDocument documentoPDF;
    private PDFRenderer renderizadorPDF;
    private int paginaActual = 0;
    private JLabel lblEstampa;


    /**
     * Creates new form frmVisualizadorPDF
     */
    public frmVisualizadorPDF() {
        initComponents();
        btnAnterior.addActionListener(e -> mostrarPagina(paginaActual - 1));
        btnSiguiente.addActionListener(e -> mostrarPagina(paginaActual + 1));
    }

    public frmVisualizadorPDF(String ruta) {
        initComponents();
        btnAnterior.addActionListener(e -> mostrarPagina(paginaActual - 1));
        btnSiguiente.addActionListener(e -> mostrarPagina(paginaActual + 1));
        System.out.println("RUTA DOCUMENTO: " + ruta);
        cargarPDF(ruta);
        mostrarEstampa();   
    }

    private void mostrarEstampa(){
        lblEstampa = new JLabel("Firma aquíiiiiiii");
        lblEstampa.setOpaque(true);
        lblEstampa.setBackground(new Color(255, 255, 200, 200)); // semi-transparente
        lblEstampa.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        lblEstampa.setVisible(false);
        lblEstampa.setSize(100, 40);  // tamaño de la estampa

        this.getLayeredPane().add(lblEstampa, JLayeredPane.POPUP_LAYER);

        jPanel1.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseMoved(MouseEvent e) {
                Point panelPoint = SwingUtilities.convertPoint(jPanel1, e.getPoint(), frmVisualizadorPDF.this.getLayeredPane());
                lblEstampa.setLocation(panelPoint.x - lblEstampa.getWidth() / 2, panelPoint.y - lblEstampa.getHeight() / 2);
                lblEstampa.setVisible(true);
            }
        });

        jPanel1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseExited(MouseEvent e) {
                lblEstampa.setVisible(false);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        btnEstampar = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 867, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        btnEstampar.setText("Estampar");

        btnAnterior.setText("Anterior");

        btnSiguiente.setText("Siguiente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAnterior)
                    .addComponent(btnSiguiente)
                    .addComponent(btnEstampar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSiguiente)
                        .addGap(18, 18, 18)
                        .addComponent(btnEstampar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVisualizadorPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVisualizadorPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVisualizadorPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVisualizadorPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVisualizadorPDF().setVisible(true);
            }
        });
    }


    public void cargarPDF(String rutaArchivo) {
        try {
            documentoPDF = PDDocument.load(new File(rutaArchivo));
            renderizadorPDF = new PDFRenderer(documentoPDF);
            paginaActual = 0;
            mostrarPagina(paginaActual);
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar PDF: " + ex.getMessage());
        }
    }

    public void mostrarPagina(int indice) {
       try {
           if (indice < 0 || indice >= documentoPDF.getNumberOfPages()) return;

           paginaActual = indice;
           BufferedImage imagen = renderizadorPDF.renderImageWithDPI(paginaActual, 150);
           int panelAncho = jPanel1.getWidth();

           double escala = (double) panelAncho / imagen.getWidth();
           int nuevoAncho = panelAncho;
           int nuevoAlto = (int) (imagen.getHeight() * escala);

           BufferedImage imagenEscalada = new BufferedImage(nuevoAncho, nuevoAlto, BufferedImage.TYPE_INT_RGB);
           Graphics g = imagenEscalada.getGraphics();
           g.drawImage(imagen, 0, 0, nuevoAncho, nuevoAlto, null);
           g.dispose();

           JPanel panelVisual = new JPanel() {
               protected void paintComponent(Graphics g) {
                   super.paintComponent(g);
                   g.drawImage(imagenEscalada, 0, 0, null);
               }
           };
           panelVisual.setPreferredSize(new Dimension(nuevoAncho, nuevoAlto));

           panelVisual.addMouseListener(new MouseAdapter() {
               public void mouseClicked(MouseEvent e) {
                   if (e.getButton() == MouseEvent.BUTTON1) {
                       int x = e.getX();
                       int y = e.getY();

                       int xOriginal = (int) (x / escala);
                       int yOriginal = (int) (y / escala);

                       System.out.println("Página " + paginaActual + " - clic en X: " + xOriginal + ", Y: " + yOriginal);
                   }
               }
           });

           jPanel1.removeAll();
           jPanel1.setLayout(new BorderLayout());
           jPanel1.add(panelVisual, BorderLayout.CENTER);
           jPanel1.revalidate();
           jPanel1.repaint();

       } catch (IOException ex) {
           ex.printStackTrace();
           JOptionPane.showMessageDialog(this, "Error al renderizar página: " + ex.getMessage());
       }
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnEstampar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
